package org.howard.edu.lsp.finalexam.question2;

/**
 * Interface for random number generation strategies.
 */
public interface RandomNumberGenerator {
    
    /**
     * Generates a positive integer using the chosen strategy.
     * 
     * @return a positive integer generated by the strategy.
     */
    int generateRandomNumber();
}
